name: cem_mpc2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy>=1.21.0
  - matplotlib>=3.5.0
  - mujoco=3.2.7
  - mypy
  - pip:
    - gymnasium
    - gymnasium-robotics
    - transforms3d
    - trimesh
    - git+https://github.com/BE2R-Lab-RND-AI-Grasping/pytorch_icem.git
  